baseurl = "http://ms-iot.github.io/windows-on-fridges/"
languageCode = "en-us"
title = "Windows on Fridges"
contentdir = "content"
publishdir = "public"
layoutdir = "layouts"
[permalinks]
  post = "windows-on-fridges/:title/"


